version: '3.8'
services: 
    phantom-app-fe:
      container_name: phantom-fe-app
      build:
        dockerfile: Dockerfile
      volumes:
        - '/usr/app'
        - '/usr/app/node_modules'
      ports:
        - 3000:3000
      environment:
        - CHOKIDAR_USEPOLLING=true