name: react CI/CD

on:
  push:
    branches: [develop, ch-configure-codeclimate-#27]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: "16.x"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js "16.x"
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
      - run: npm i
      - run: npm run build --if-present

       test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macOS-latest ]
        node: "16.x"
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@develop
    - uses: actions/setup-node@develop
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm run build
    - run: npm run test

  coverage:
    needs: [test]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@develop
      - name: Use Node.js "16.x"
        uses: actions/setup-node@develop
        with:
          node-version: "16.x"
          cache: "npm"

    - run: npm  install
    - run: npm run build
      - uses: paambaati/codeclimate-action@v2.5.0
        env:
          CI: "true"
          CC_TEST_REPORTER_ID: 5571bb146a6c68ba2b7186eb7ca0ca2b57ec5a506f0b2f2deb8c1a5e12afd728
        with:
          debug: true
          coverageCommand: npm run coverage