name: CI

on:
  push:
    branches: [  ch-configure-codeclimate-#27]
  pull_request:
    branches: [ ch-configure-codeclimate-#27 ]


  workflow_dispatch:
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
              node-version: '16.x'


      - name: install all dependence
        run: npm install
    
      - name: run build
        run: npm run build --if-present


  coverage:
    needs: [build]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x'
        uses: actions/setup-node@v3
        with:
          node-version: 16.x'
          cache: "npm"
      - run: npm i
      - uses: paambaati/codeclimate-action@v2.5.0
        env:
          CI: "true"
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          debug: true
          coverageCommand: npm run coverage

